#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

SECRETSDIR="${HOME}/.launchpad-secrets"
mkdir -p "${SECRETSDIR}"
cd "${SECRETSDIR}"
echo "${LAUNCHPAD_ID_RSA_BASE64}" | base64 -d > id_rsa
echo "${LAUNCHPAD_SIGNING_KEY_BASE64}" | base64 -d > launchpad-key.asc
echo "${LAUNCHPAD_SIGNING_KEY_PASSPHRASE_BASE64}" | base64 -d > launchpad-key.passphrase
