#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SECRETSDIR="${SCRIPTDIR}/../secrets"
mkdir -p "${SECRETSDIR}"
gpg --quiet --batch --yes --decrypt --passphrase="${LAUNCHPAD_SECRET_PASSPHRASE}" "${SCRIPTDIR}/launchpad.tar.gpg" | tar x -C "${SECRETSDIR}"
