#!/bin/bash

usage()
{
    cat <<EOF
Local development setup for edi.

This script enables bash completion and adds
the local bin folder to the PATH environment
variable. The changes only affect the current
bash session.

Usage:

source $(basename "${BASH_SOURCE[0]}")
EOF
}

print_error_and_exit()
{
    >&2 echo -e "\nError: $1"
    exit 1
}

SCRIPTDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Hint: $0 might be "-bash" if logged in via ssh.
if [ "$(basename "x/$0")" == "$(basename "${BASH_SOURCE[0]}")" ]
then
    usage
    print_error_and_exit "Please do not run this script directly."
fi

# make edi also available via sudo edi
# bash manual:
# If the last character of the alias value is a space or
# tab character, then the next command word following the
# alias is also checked for alias expansion. 
alias sudo="sudo "
alias edi="${SCRIPTDIR}/bin/edi"

# add the bin folder to the path
BINFOLDER="${SCRIPTDIR}/bin"
if [[ ! ":$PATH:" == *":${BINFOLDER}:"* ]]
then
    export PATH=${BINFOLDER}:${PATH}
fi

# enable bash completion
eval "$(register-python-argcomplete3 edi)"

