#!/bin/bash

set -e

find /usr/share/doc -depth -type f ! -name copyright|xargs rm || true
find /usr/share/doc -empty|xargs rmdir || true
rm -rf /usr/share/man /usr/share/groff /usr/share/info
rm -rf /usr/share/lintian /usr/share/linda /var/cache/man

echo "Documentation removed to save disk space!" > /usr/share/README.doc.edi
