#!/bin/sh
set -e

case "$1" in
    configure)
        mkdir -p /etc/bash_completion.d
        if command -v register-python-argcomplete3 > /dev/null
        then
            register-python-argcomplete3 edi > /etc/bash_completion.d/edi
        else
            # python3-argcomplete >= 2.0
            register-python-argcomplete edi > /etc/bash_completion.d/edi
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0