name: edi package build
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       include:
         - distribution: debian
           distribution_release: bullseye
           repository_type: packagecloud
         - distribution: ubuntu
           distribution_release: "20.04"
           repository_type: launchpad
    steps:
      - name: Echo job details
        env:
          DISTRIBUTION: ${{ matrix.distribution }}
          DISTRIBUTION_RELEASE: ${{ matrix.distribution_release }}
          REPOSITORY_TYPE: ${{ matrix.repository_type }}
        run: echo "${DISTRIBUTION}/${DISTRIBUTION_RELEASE} --> ${REPOSITORY_TYPE}"
      - name: Check out the source code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull docker container
        run: docker pull "${DISTRIBUTION}":"${DISTRIBUTION_RELEASE}"
        env:
          DISTRIBUTION: ${{ matrix.distribution }}
          DISTRIBUTION_RELEASE: ${{ matrix.distribution_release }}
      - name: Decode launchpad secrets
        run: ./.github/scripts/decode-secrets
        env:
          LAUNCHPAD_ID_RSA_BASE64: ${{ secrets.LAUNCHPAD_ID_RSA_BASE64 }}
          LAUNCHPAD_SIGNING_KEY_BASE64: ${{ secrets.LAUNCHPAD_SIGNING_KEY_BASE64 }}
          LAUNCHPAD_SIGNING_KEY_PASSPHRASE_BASE64: ${{ secrets.LAUNCHPAD_SIGNING_KEY_PASSPHRASE_BASE64 }}
      - name: Run build job within container
        run: docker run -v $(pwd):/data/runner -v ${HOME}/.launchpad-secrets:/data/secrets "${DISTRIBUTION}":"${DISTRIBUTION_RELEASE}" bash -c "/data/runner/.github/scripts/build-package"
        env:
          DISTRIBUTION: ${{ matrix.distribution }}
          DISTRIBUTION_RELEASE: ${{ matrix.distribution_release }}
      - name: Upload package to launchpad repository
        run: docker run -v $(pwd):/data/runner -v ${HOME}/.launchpad-secrets:/data/secrets "${DISTRIBUTION}":"${DISTRIBUTION_RELEASE}" bash -c "/data/runner/.github/scripts/upload-package-launchpad ${GITHUB_REF##*/} ${LAUNCHPAD_USER} ${LAUNCHPAD_REPOSITORY}"
        env:
          DISTRIBUTION: ${{ matrix.distribution }}
          DISTRIBUTION_RELEASE: ${{ matrix.distribution_release }}
          LAUNCHPAD_USER: ${{ secrets.LAUNCHPAD_USER }}
          LAUNCHPAD_REPOSITORY: ${{ secrets.LAUNCHPAD_REPOSITORY }}
        if: matrix.repository_type == 'launchpad'
