name: edi package build
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       include:
         - distribution: debian
           distribution_release: bullseye
           repository_type: packagecloud
         - distribution: ubuntu
           distribution_release: "20.04"
           repository_type: launchpad
    steps:
      - name: Echo job details
        env:
          DISTRIBUTION: ${{ matrix.distribution }}
          DISTRIBUTION_RELEASE: ${{ matrix.distribution_release }}
          REPOSITORY_TYPE: ${{ matrix.repository_type }}
        run: echo "${DISTRIBUTION}/${DISTRIBUTION_RELEASE} --> ${REPOSITORY_TYPE}"
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

